# Generated by Django 4.1.1 on 2022-09-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
