# Generated by Django 4.1.1 on 2022-09-23 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photoproject', '0005_photo_receipt_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
