# Generated by Django 4.1.1 on 2022-09-23 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoproject', '0006_alter_receipt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='photoproject.category'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
