# Generated by Django 4.1.1 on 2022-09-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoproject', '0008_receipt_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
