# Generated by Django 4.1.1 on 2022-09-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoproject', '0011_receipt_business_receipt_company_receipt_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='file_document',
            field=models.FileField(null=True, upload_to='exel/Data%y/%m/%d/'),
        ),
    ]
