# Generated by Django 4.0.7 on 2022-09-29 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoproject', '0012_receipt_file_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_document', models.FileField(null=True, upload_to='exel/Data%y/%m/%d/')),
                ('date', models.DateField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photoproject.project')),
            ],
        ),
    ]
