# Generated by Django 4.0.7 on 2022-09-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoproject', '0013_projectreceipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreceipts',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
