# Generated by Django 4.1.1 on 2022-09-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_first_name_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
