# Generated by Django 4.0.7 on 2022-10-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_account_number_user_birthdate_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
